// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/scionproto/scion/private/hummingbirddb (interfaces: DB)

// Package mock_hummingbirddb is a generated GoMock package.
package mock_hummingbirddb

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	addr "github.com/scionproto/scion/pkg/addr"
	hummingbird "github.com/scionproto/scion/pkg/hummingbird"
	hummingbirddb "github.com/scionproto/scion/private/hummingbirddb"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// BeginTransaction mocks base method.
func (m *MockDB) BeginTransaction(arg0 context.Context, arg1 *sql.TxOptions) (hummingbirddb.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTransaction", arg0, arg1)
	ret0, _ := ret[0].(hummingbirddb.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTransaction indicates an expected call of BeginTransaction.
func (mr *MockDBMockRecorder) BeginTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTransaction", reflect.TypeOf((*MockDB)(nil).BeginTransaction), arg0, arg1)
}

// ListFlyovers mocks base method.
func (m *MockDB) ListFlyovers(arg0 context.Context, arg1 []addr.IA) ([]*hummingbird.Flyover, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlyovers", arg0, arg1)
	ret0, _ := ret[0].([]*hummingbird.Flyover)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlyovers indicates an expected call of ListFlyovers.
func (mr *MockDBMockRecorder) ListFlyovers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlyovers", reflect.TypeOf((*MockDB)(nil).ListFlyovers), arg0, arg1)
}
